# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abbreviation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_short', models.TextField()),
                ('abbreviation', models.CharField(max_length=100)),
                ('classification', models.CharField(choices=[(0, 'invalid'), (1, 'simple'), (2, 'complex'), (3, 'substring')], max_length=100)),
            ],
        ),
    ]
