# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abbr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abbreviation',
            old_name='long_short',
            new_name='long_form',
        ),
        migrations.AlterField(
            model_name='abbreviation',
            name='classification',
            field=models.CharField(choices=[(0, 'unrelated'), (1, 'simple'), (2, 'complex'), (3, 'substring')], max_length=100, null=True),
        ),
    ]
