# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abbr', '0002_auto_20160211_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abbreviation',
            name='classification',
            field=models.IntegerField(choices=[(0, 'unrelated'), (1, 'simple'), (2, 'complex'), (3, 'substring')], max_length=100, null=True),
        ),
    ]
